# Generated by Django 4.2.5 on 2023-11-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20210729_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='Profilepicture',
            field=models.ImageField(default='default.jpg', upload_to='profilepic/'),
        ),
    ]
